version: "3.9"

services:
    backend:
        build:  ./backend
        container_name: backend
        command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
        volumes:
            - ./backend:/usr/src/app
        ports:
            - "8000:8000"
        depends_on:
            - db
    db:
        image: postgres
        container_name: db
        environment:
            - POSTGRES_PASSWORD=postgres
    redis:
        image: "redis:alpine"
        ports:
            - "6379:6379"