version: "3.8"
   
services:
    django:
        build: .
        container_name: django
        command: python manage.py runserver 0.0.0.0:8000
        volumes:
            - ./backend:/usr/src/app/
        ports:
            - "8000:8000"
        environment:
            - POSTGRES_NAME=postgres
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD={DB_PASSWORD}
        env_file:
            - .env
        depends_on:
            - pgdb
            - redis
    celery:
        build: .
        command: celery -A altfighter worker -l INFO
        volumes:
            - .:/usr/src/app
        environment:
            - POSTGRES_NAME=postgres
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD={DB_PASSWORD}
        env_file:
            - .env
        depends_on:
            - django
            - redis
    pgdb:
        image: postgres
        container_name: pgdb
        environment:
            - POSTGRES_DB=postgres
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD={DB_PASSWORD}
        volumes:
            - pgdata:/var/lib/postgresql/data/
    redis:
        image: "redis:alpine"
        ports:
            - "6379:6379"
        
volumes:
    pgdata:
