version: "3.9"

services:
    backend:
        build:  ./backend
        container_name: backend
        env_file:
            - .local.env
        command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
        volumes:
            - ./backend:/usr/src/app
        ports:
            - "8000:8000"
        depends_on:
            - db
    frontend:
        container_name: frontend
        command: "ng serve --host 0.0.0.0 --disable-host-check"
        build: ./frontend
        ports:
            - "4200:4200"
            - '49153:49153'
        volumes:
            - ./frontend/:/app/
            - node_modules:/app/node_modules
            - angular_cache:/app/.angular/cache/
        depends_on:
            - backend
    db:
        image: postgres
        container_name: db
        environment:
            - POSTGRES_PASSWORD=postgres
        env_file:
            - .local.env
    redis:
        image: "redis:alpine"
        ports:
            - "6379:6379"
volumes:
    node_modules:
    angular_cache: