version: "3.8"

services:
  backend:
    build:
      context: backend
      dockerfile: ./compose/local/django/Dockerfile
    image: django_celery_backend
    command: /start
    volumes:
      - ./backend:/app
    ports:
      - 8000:8000
    env_file:
      - env/.local.env
    depends_on:
      - redis
      - db

  db:
    image: postgres:14-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - env/.local.env

  redis:
    image: redis:7-alpine

  celery_worker:
    build:
      context: backend
      dockerfile: ./compose/local/django/Dockerfile
    image: django_celery_worker
    command: /start-celeryworker
    volumes:
      - ./backend:/app
    env_file:
      - env/.local.env
    depends_on:
      - redis
      - db

  celery_beat:
    build:
      context: backend
      dockerfile: ./compose/local/django/Dockerfile
    image: django_celery_beat
    command: /start-celerybeat
    volumes:
      - ./backend:/app
    env_file:
      - env/.local.env
    depends_on:
      - redis
      - db

  flower:
    build:
      context: backend
      dockerfile: ./compose/local/django/Dockerfile
    image: django_celery_flower
    command: /start-flower
    volumes:
      - ./backend:/app
    env_file:
      - env/.local.env
    ports:
      - 5557:5555
    depends_on:
      - redis
      - db

volumes:
  postgres_data:
