# Generated by Django 4.1.3 on 2022-12-07 00:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("item", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="name",
            field=models.CharField(max_length=30, null=True),
        ),
    ]
