# Generated by Django 4.1.3 on 2022-12-09 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("character", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="character",
            name="nickname",
            field=models.CharField(max_length=30, null=True, unique=True),
        ),
    ]
