name: Django CI

on:
  push:
    branches: ["main", "production"]
  pull_request:
    branches: ["main", "production"]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
    env:
      python-version: "3.10"
      SECRET_KEY: secret
      DEBUG: true
      ALLOWED_HOSTS: "*"
      ENGINE_NAME: postgresql
      DB_NAME: postgres
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_HOST: db
      DB_PORT: 5432
      POSTGRES_PASSWORD: postgres
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ env.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ env.python-version }}
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r backend/requirements.txt
      - name: Run Tests
        run: |
          python backend/manage.py test
